# Generated by Django 5.1.7 on 2025-06-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthcareApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthstat',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
