# Generated by Django 5.1.7 on 2025-05-06 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthcareApp', '0002_workoutsession_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('water_intake', models.FloatField(default=0)),
                ('step_count', models.IntegerField(default=0)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
