# Generated by Django 5.1.7 on 2025-04-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthcareApp', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutritiongoal',
            old_name='daily_protein',
            new_name='daily_proteins',
        ),
        migrations.RenameField(
            model_name='nutritionplan',
            old_name='total_protein',
            new_name='total_proteins',
        ),
    ]
