# Generated by Django 5.1.7 on 2025-06-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthcareApp', '0002_alter_healthstat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthstat',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
