# Generated by Django 5.1.7 on 2025-06-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthcareApp', '0002_add_role_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthstat',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='calories_burned',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='total_duration',
            field=models.IntegerField(default=0),
        ),
    ]
