# Generated by Django 5.1.7 on 2025-04-01 15:40

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthcareApp', '0002_fooditem_musclegroup_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(null=True)),
                ('daily_calories', models.FloatField(default=None)),
                ('daily_protein', models.FloatField(default=None)),
                ('daily_carbs', models.FloatField(default=None)),
                ('daily_fats', models.FloatField(default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='type',
            new_name='reminder_type',
        ),
        migrations.AddField(
            model_name='diary',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='diary',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='calories',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='carbs',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fats',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='protein',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='quantity',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='message',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='total_calories',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='total_carbs',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='total_fats',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='total_protein',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='reminder',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='repeat',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='bpm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='calories_burned',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='goal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='schedule',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='steps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='total_duration',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='calories_burned',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='rating',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='repetition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='exercise',
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('sender_1', 'sender_2'), name='unique_conversation'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(('sender_1__lt', models.F('sender_2'))), name='check_sender_order'),
        ),
        migrations.AddField(
            model_name='nutritiongoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='exercise',
            field=models.ManyToManyField(related_name='workout_sessions', to='HealthcareApp.exercise'),
        ),
    ]
