# Generated by Django 5.1.7 on 2025-06-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthcareApp', '0003_alter_healthstat_date_alter_nutritionplan_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionplan',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
