# Generated by Django 5.1.7 on 2025-04-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthcareApp', '0003_nutritiongoal_rename_type_reminder_reminder_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='nutritiongoal',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
