# Generated by Django 5.1.7 on 2025-05-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthcareApp', '0004_exercise_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weight',
        ),
    ]
