# Generated by Django 5.1.7 on 2025-04-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthcareApp', '0004_conversation_name_nutritiongoal_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='Message', max_length=100),
        ),
    ]
