# Generated by Django 5.1.7 on 2025-05-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthcareApp', '0005_remove_user_height_remove_user_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthstat',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
