# Generated by Django 5.1.7 on 2025-05-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthcareApp', '0005_remove_user_height_remove_user_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthstat',
            name='height',
        ),
        migrations.RemoveField(
            model_name='healthstat',
            name='weight',
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
