# Generated by Django 5.1.7 on 2025-05-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthcareApp', '0006_remove_healthstat_height_remove_healthstat_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weight',
        ),
        migrations.AddField(
            model_name='healthstat',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthstat',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
