# Generated by Django 5.1.7 on 2025-05-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthcareApp', '0007_remove_user_height_remove_user_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
