# Generated by Django 5.1.7 on 2025-06-03 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthcareApp', '0006_alter_healthstat_date'),
        ('HealthcareApp', '0008_remove_user_role_user_height_user_weight_and_more'),
    ]

    operations = [
    ]
