# Generated by Django 5.1.7 on 2025-06-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthcareApp', '0010_remove_message_conversation_remove_message_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='bpm',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='steps',
        ),
    ]
