# Generated by Django 5.1.7 on 2025-06-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthcareApp', '0011_remove_workoutsession_bpm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='bpm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='steps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
